#!/usr/bin/env python3
import json
import os
from pathlib import Path

# Paths
this_dir = Path(__file__).resolve().parent
output_root = (this_dir.parent / "output").resolve()
characters_root = output_root / "characters"

# Load manifests
manifests = []
for mf in [output_root / "videos_manifest.json", characters_root / "videos_manifest.json"]:
    if mf.exists():
        with mf.open("r", encoding="utf-8") as f:
            try:
                manifests.extend(json.load(f))
            except Exception as e:
                print(f"Warning: failed to load {mf}: {e}")

# Also include ad-hoc MP4s (e.g., creatures) that are not in manifests
extra_mp4s = []
for mp4 in output_root.rglob("*.mp4"):
    # Skip ones already represented in manifests by matching 'out'
    already = any(Path(entry.get("out", "")).resolve() == mp4.resolve() for entry in manifests)
    if not already:
        extra_mp4s.append(mp4)

items = []

# Helper to append one output path
from typing import Optional

def add_item(out_path: Path, fps: Optional[int]=None, frames: Optional[int]=None):
    if not out_path.exists():
        return
    rel = os.path.relpath(out_path, start=this_dir).replace("\\", "/")
    is_char = str(out_path).lower().find(str(characters_root).lower()) != -1
    category = "characters" if is_char else ("creatures" if "/output/creatures/" in out_path.as_posix() else "general")

    group = None
    variant = None
    animation = out_path.stem

    if category == "characters":
        try:
            after = out_path.as_posix().split("/output/characters/")[1]
            tokens = after.split("/")
            if tokens:
                group = tokens[0]
            if len(tokens) >= 3:
                variant = tokens[1]
                animation = Path(tokens[-1]).stem
            elif len(tokens) == 2:
                group = tokens[0]
                animation = Path(tokens[1]).stem
            animation = animation.replace("_", " ")
        except Exception:
            pass
    elif category == "creatures":
        # Use folder structure after /output/creatures/
        try:
            after = out_path.as_posix().split("/output/creatures/")[1]
            tokens = after.split("/")
            if len(tokens) >= 2:
                group = tokens[0]  # top-level creature name folder if any
                animation = Path(tokens[-1]).stem
        except Exception:
            pass
        animation = animation.replace("_", " ")
    else:
        animation = out_path.stem.replace("_", " ")

    name_parts = []
    if category in ("characters", "creatures"):
        if group:
            name_parts.append(group)
        if variant and variant.lower() != "png sequences":
            name_parts.append(variant)
        name_parts.append(animation)
    else:
        name_parts.append(animation)
    display_name = " / ".join([p for p in name_parts if p])

    items.append({
        "id": 0,
        "category": category,
        "group": group,
        "variant": variant,
        "animation": animation,
        "name": display_name,
        "src": rel,
        "fps": fps,
        "frames": frames,
    })

# Add items from manifests
for entry in manifests:
    out_path = Path(entry.get("out", "")).resolve()
    add_item(out_path, entry.get("fps"), entry.get("frames"))

# Add extra discovered MP4s
for mp4 in extra_mp4s:
    add_item(mp4.resolve())

# Sort consistently
items.sort(key=lambda x: (x["category"], x.get("group") or "", x.get("variant") or "", x["name"]))

# Assign IDs
for i, it in enumerate(items):
    it["id"] = i

# Write manifest.js for easy local use without CORS
manifest_js = this_dir / "gallery_manifest.js"
with manifest_js.open("w", encoding="utf-8") as f:
    f.write("// Auto-generated by build_manifest.py\n")
    f.write("window.ANIMATIONS = ")
    json.dump(items, f, ensure_ascii=False, indent=2)
    f.write(";\n")

print(f"Wrote {manifest_js} with {len(items)} items.")
